### ISSUE TITLE
Default new setting for put method is wrong for Mongoose 4.

### ISSUE THREAD

**Issue by puradawid** [baugarten/node-restful#106]
Regarding to Mongoose docs: http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate:

> new: bool - if true, return the modified document rather than the original. defaults to false (changed in 4.0)

So defaults provided in mongoose:

    defaults = function() {
      return {
        routes: {},
        allowed_methods: {
          get: { detail: false }
        },
        update_options: {},
        remove_options: {},
        templateRoot: '',
        shouldIncludeSchema: true,
        shouldUseAtomicUpdate: true
      };
    };

should have a ```defaults.update_options.new = true```. It would be backward compatible.

**Comment by baugarten** [comment]
The goal was not for node-restful to be backwards compatible. We aren't 1.0 so we're not doing true semver -- minor version bumps are not guaranteed to be API compatible.

node-restful is not meant to abstract out the database layer completely, so it doesn't make sense to me to have defaults that conflict with those of the ODM we're using (i.e. mongoose)
