### ISSUE TITLE
Inconsistent 404 behavior

### ISSUE THREAD

**Issue by nutic** [baugarten/node-restful#108]
There are some cases when I expect to get 404 status in response but get 200 or even exceptions.
Tests explaining and fixes are in https://github.com/baugarten/node-restful/pull/104
Please merge.

**Comment by romain10009** [comment]
is this related to handlers.js line 125 missing a return statement ? (like this : "return next();")

**Comment by romain10009** [comment]
line 111 look strange too...

**Comment by nutic** [comment]
> is this related to handlers.js line 125 missing a return statement ? (like this : "return next();")

Exactly. Execution flow goes further and ails on ``docToUpdate.set(...)`` as ``docToUpdate`` is null

> line 111 look strange too...

Could you please add comment to PR itself? I'm not sure what line 111 you mean.
