### ISSUE TITLE
I want to get rows randomly sorted.

### ISSUE THREAD

**Issue by knightkill** [baugarten/node-restful#110]
Is there anyway I can get rows in random order?

**Comment by baugarten** [comment]
There doesn't really seem to be a great way to do this with mongoose. A quick google search turned this up -- http://stackoverflow.com/questions/27348811/possible-to-retrieve-multiple-random-non-sequential-documents-from-mongodb

I would recommend implementing this using a custom route

**Comment by baugarten** [comment]
Haven't heard back in a while and this isn't something that I believe belongs in this library.

**Comment by knightkill** [comment]
Sorry, I got bit addicted to gaming. Really wont happen again. :)
