### ISSUE TITLE
Is not possible populated sub-entity's related row's populate?

### ISSUE THREAD

**Issue by frknbasaran** [baugarten/node-restful#111]
I need help about this too, 

![zasdas](https://cloud.githubusercontent.com/assets/6316032/10710128/0330d4b6-7a53-11e5-9bc9-68519ff4eaef.png)

I can get first entity's populated rows but can't sub-entity's properties.

In example:
```javascript
Object.created_by // is populated with related model but 
Object.answers[0].created_by // is not populated.

```

**Comment by frknbasaran** [comment]
When i add new populate param as "populate=answers.created_by" problem was solved. :+1:

**Comment by rof20004** [comment]
I tried and not works, can you help me?

This is my url: http://localhost:8080/api/v1/?populate=client&populate=client.card

If I use http://localhost:8080/api/v1/?populate=client

It works, gives me all client values, but inside client I have a card, and with this url not works.

**Comment by rof20004** [comment]
@frknbasaran
