### ISSUE TITLE
I can't modify res.locals.bundle from query results

### ISSUE THREAD

**Issue by dialog** [baugarten/node-restful#113]
Hi,

I'm trying to modify the results of a query like:

```
Artist.methods(['get', 'put', 'post', 'delete']);
Artist.after('get', function(req, res, next) {
	res.locals.bundle.forEach(function(artist, index) {
		artist.albums = count; // Updates res.locals.bundle[index]['albums']
		ArtistAlbum.count({artistId:artist._id}, function(err, count) {
			if (count > 0) {
				artist.albums = count; // Doesn't update res.locals.bundle[index]['albums']
			}
		});
	});
	next();
});
Artist.register(router, '/artists');
```

So, modifying `res.locals.bundle` outside of the `ArtistAlbum.count()` query works but when I do it inside - as I want to use data from the query - it doesn't work.

Seems like a bug to me, or am I doing something wrong?

Thanks in advance.

**Comment by baugarten** [comment]
This looks like a problem with the order of operations and the async nature of javascript.

`next()` will get called before the callback you pass to `ArtistAlbum.count(...)` gets called, so you never modify `res.locals.bundle`.

You need to call `next` exactly once after all of the callbacks have returned. One way to do this is to use `after()` from underscore -- http://underscorejs.org/#after

`next = _.after(res.locals.bundle.length, next);`

i.e. only call the real `next` function after I call `next` this many times. Then you can call `next()` each time you get a count result.

You can also take a look at https://github.com/caolan/async

**Comment by dialog** [comment]
Thanks for the quick response.

I have used underscore's `_.after()` method and it didn't quite work. The way I was able to get it to work was:

```
Artist.methods(['get', 'put', 'post', 'delete']);
Artist.after('get', function(req, res, next) {
    res.locals.bundle.forEach(function(artist, index) {
        ArtistAlbum.count({artistId:artist._id}, function(err, count) {
            if (count > 0) {
                artist.albums = count;
            }
            if (index == res.locals.bundle.length - 1) {
                next();
            }
        });
    });
});
Artist.register(router, '/artists');
```

Thanks.
