### ISSUE TITLE
GET /resource/:id not working for Mongoose Schemas with "length" field!

### ISSUE THREAD

**Issue by jkonert** [baugarten/node-restful#116]
Using Schemas like: 
var resource = new Schema({
    title:  { type: String, required: true},
    src:    { type: String, required: true},
    length: { type: Number, min: 0, required: true},
});
lead to empty results when querying GET /resource/:id   . POST and GET of full list work.

I found out that the name "length" in the Schema seems to be the problem.

**Comment by baugarten** [comment]
Thanks for the reproducible test case -- made this fairly easy to track down.

Looks like I added a hack when handling array results vs object results that relied on the `length` property.

I released the fix in version 0.2.3 & added a regression test :beers:
