### ISSUE TITLE
is there a way to make it create in order indexed IDs ?

### ISSUE THREAD

**Issue by nemr** [baugarten/node-restful#148]
Hi , 

This is a really great npm , I just wanted to ask you if there is a way in which it can index the ID in an acceding order instead of long random id ?

**Comment by pkleckner** [comment]
I actually just did that a few minutes ago. Here's how I did it:

Install the `mongoose-auto-increment` package (https://github.com/chevex-archived/mongoose-auto-increment)


`npm install mongoose-auto-increment`

Afterwards, change the server.js file to something like:

```
var express = require('express');
var mongoose = require('mongoose'), autoIncrement = require('mongoose-auto-increment');
var bodyParser = require('body-parser');

var connection = mongoose.connect('mongodb://localhost/your-database-name');

autoIncrement.initialize(connection);

var app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use('/api', require('./routes/api'));

app.listen(4000);
console.log('API is running on port 4000');
```

This did 3 things:

1. It added `, autoIncrement = require('mongoose-auto-increment')` to the mongoose variable declaration,
2. Put the mongoose connection into a variable,
3. Initialized autoIncrement using the connection.

Then in your model, something like:

```
var restful = require('node-restful');
var mongoose = restful.mongoose;
var autoIncrement = require('mongoose-auto-increment');

var exampleSchema = new mongoose.Schema({
    example: String,
});

exampleSchema.plugin(autoIncrement.plugin, 'Example');

module.exports = restful.model('Example', exampleSchema);
```

This declared autoIncrement and ran the Schema through it before exporting it out to the router.

One thing to note is that the increments starts at 0, not 1. I don't see why that would be a big deal, but just wanted to let you know.

Hope that helps!
