### ISSUE TITLE
Add support for populating on /

### ISSUE THREAD

**Issue by OmgImAlexis** [baugarten/node-restful#153]
From what I can see you can't currently populate the root path.

For example `/book/?populate=author` doesn't work yet `/book/00000/?populate=author` does.

**Comment by noizbuster** [comment]
```
/book?populate=author
/book/00000?populate=author
```
Try after remove last slash on your url
It should works.

**Comment by OmgImAlexis** [comment]
@baugarten maybe this is a bit of a bug since some places require an ending slash to work and others don't. Maybe settle on one, both or give an option to change it either way.
