### ISSUE TITLE
Populate array sub-entity of array sub-entity

### ISSUE THREAD

**Issue by traschke** [baugarten/node-restful#156]
![image](https://cloud.githubusercontent.com/assets/5337580/23719113/55290e1a-043a-11e7-9bc0-8dc281b3a817.png)

I populated a sub-entity which is an array. This works as expected with the URL parameter `populate=unitparts`.
Underlying `unitparts` is an array-sub-entity called `groups`, which I also want to populate.
`populate=unitparts.groups` does not work.

The full query I used is:
`http://localhost:3000/api/offer/58c0517e31570a0ae042765b?populate=unitparts&populate=unitparts.groups&populate=teachers`

**Comment by rof20004** [comment]
I have the same problem. Did you solved?

**Comment by rof20004** [comment]
@traschke

**Comment by traschke** [comment]
No, I didn't solve the problem. I ended up calling the unpopulated ressources separately.
