### ISSUE TITLE
Case insensitive

### ISSUE THREAD

**Issue by cyates81** [baugarten/node-restful#54]
Hello, how would I do a case insensitive filter?

?key__regex=value

will not work because there is no way to specify regex options in the query from what I can tell.

Thanks,

Chris

**Comment by vedant** [comment]
+1 Having the same issue.

**Comment by baugarten** [comment]
Check out https://github.com/baugarten/node-restful/commit/5f1a80a51d82f1fb37800c7dad41f5183ec3d096#diff-2644a31e1dad28ae5f900df1ecff9986R151

This is realeased in version 0.2.2 -- let me know if that doesn't solve your problem or you have any issues

**Comment by vedant** [comment]
Phenomenal, I had just forked and was about to issue a pull request for a less elegant solution. Thank you!
