### ISSUE TITLE
schema pre `save` and `remove` are not executed

### ISSUE THREAD

**Issue by saelfaer** [baugarten/node-restful#73]
When binding pre `save` and `remove` functionality to the schema it is bypassed when using node-restful. 

```` js
var restful = require('node-restful'),
    mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var UserSchema = new Schema({
    lastName: {
        type: String,
        required: true
    },
    firstName: {
        type: String,
        required: true
    }
});

UserSchema.pre("save", function (next) {
    console.log('Backup old version before save...');
    return next();
});

restful.model('User', UserSchema).methods(['get', 'delete', 'put', 'post']);
````

This is a problem when using it together with a versioning module like [fghibellini/mongoose-version2](/fghibellini/mongoose-version2) as they heavy rely on these hooks.

**Comment by arturskeeled** [comment]
@saelfaer @baugarten 
Any idea if this pre hook will be implemented soon or at all?
Thanks in advance!

**Comment by saelfaer** [comment]
@arturskeeled This should be available. this issue is probably overlooked but can be closed. The functionality you need is available in the PR #75 which is linked to this issue.

setting `shouldUseAtomicUpdate` option to false will fire the events you need. This option defaults to `true` so it doesn't introduce a breaking change when that option was added.

**Comment by arturskeeled** [comment]
@saelfaer 
Thanks, but where should i set `shouldUseAtomicUpdate: true` ?

**Comment by saelfaer** [comment]
taking my example from above, pass the options as arguments to the restful.model method:

```
var restful = require('node-restful'),
    mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var UserSchema = new Schema({
    lastName: {
        type: String,
        required: true
    },
    firstName: {
        type: String,
        required: true
    }
});

UserSchema.pre("save", function (next) {
    console.log('Backup old version before save...');
    return next();
});

restful.model({
    title: 'User',
    methods: ['get', 'delete', 'put', 'post'],
    schema: UserSchema,
    shouldUseAtomicUpdate: false
});
```

**Comment by TiagoGouvea** [comment]
Calling this way ```.model({...,shouldUseAtomicUpdate: false})``` don't work for me. But this works: 

```
this.resource = app.resource = restful.model('user', mongooseSchema).methods(['get', 'post', 'put', 'delete']).updateOptions({'new': true});
this.resource.shouldUseAtomicUpdate = false;
```
