### ISSUE TITLE
GET should return 404 (Not Found), if ID not found or invalid

### ISSUE THREAD

**Issue by amrynsky** [baugarten/node-restful#81]
Currently if object with specified ID is not found the empty response is returned with status 200 (OK). In case ID is invalid - status is 500.

Would be better to return 404 (Not Found) in case object with specified ID is not found or invalid
http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by amrynsky** [comment]
The same problem is for PUT requests. In case object with the specified ID is not found - status is 400 (Bad Request) and body is {"status":404,"message":"Object not found","name":"ObjectNotFound","errors":{"_id":{"message":"Could not find object with specified attributes"}}}.

The expected behaviour would be to get status 404.

**Comment by kirkov** [comment]
I was sure I was doing something wrong, but I guess not :) - it seems pretty basic...

Headers retuned:

	Connection	keep-alive
	Date	Wed, 11 Feb 2015 19:42:50 GMT
	Transfer-Encoding	chunked
	X-Powered-By	Express

**Comment by baugarten** [comment]
Fixed the last of these in fe5a70c9b4a19110c26f4c15814614dbfbeb770b -- kind of embarrassing past me thought 400 was the correct behavior. Thanks for filing this
