### ISSUE TITLE
TypeError: Cannot call method &#39;where&#39; of undefined in version 0.1.18

### ISSUE THREAD

**Issue by icompuiz** [baugarten/node-restful#82]
I am having trouble pin pointing the cause of an error.

I have 'before' middleware that will append a search condition the ```quer``` object on ```req```.

```
resource.before('get', function(req, res, next) {		

		req.quer.where({
			name: {
				$ne: 'value'
			}
		});
		
		next();

	});
```

but am getting an error message 'TypeError: Cannot call method &#39;where&#39; of undefined'

I have dug into the source to identify where ```req.quer``` is being set and, using console messages, I've identified that the Model::preprocess method that sets ```req.quer``` is not called at all. 

This functionality worked fine in 0.1.17. Is this a known issue, a regression, or am I doing something wrong?

- Thanks

**Comment by baugarten** [comment]
The implementation detail of `req.quer` is not exposed. The appropriate way to do this would be to modify the request here. So, this would instead look like 

```js
resource.before('get', function(req, res, next) {       

        req.body.name = 'value'; 
        next();

    });
```

Then the library will correctly format this into the mongoose query
