### ISSUE TITLE
Help, how to upload images via node-restful?

### ISSUE THREAD

**Issue by aa21** [baugarten/node-restful#89]
I've looked all over but I'm not able to find any examples. Please provide example schema setup for an api endpoint that will accept image (or data) files. Thanks!

**Comment by adriangordon1231** [comment]
This would be very useful indeed.

**Comment by OmgImAlexis** [comment]
Since this heavily relies on MongoDB and Mongoose you're honestly better off either setting a field for URL or using something else. MongoDB really isn't best for storing binary data.

What exactly are you trying to do with this?

**Comment by baugarten** [comment]
Yeah, the way to do this is to upload the image on the client side and then save the document with the URI to the image.

**Comment by aa21** [comment]
@baugarten  @OmgImAlexis  Of course nobody would suggest to save to the db. When users upload an image (or document), we want the API to be able to handle that and redirect that image to be saved in a server folder (e.g uploads), and as @baugarten suggested, save the uri in db and return it to client. 

This issue was closed based on an assumption ('saving image to db') without an answer to the real issue. Please reopen or address the issue, thanks.

**Comment by OmgImAlexis** [comment]
Maybe a data blob/url feature can be added to allow data to be added via a blob in the db, via a hook so it can be uploaded to amazon's S2, etc.
