### ISSUE TITLE
POST not fully working

### ISSUE THREAD

**Issue by lakano** [baugarten/node-restful#90]
Hello !

Thanks for your package :)

I have installed it :
```shell
$ npm install node-restful
$ npm install express
$ npm install body-parser
```

I have copied the default example, with some updates for body-parser (found in a ticket) :
```javascript
var express = require('express'),
    bodyParser = require('body-parser'),
    restful = require('node-restful'),
    mongoose = restful.mongoose;
var app = express();

var config = {
    port: 4000
};

app.use(bodyParser.json());
app.use(express.query());

mongoose.connect("mongodb://localhost/trackers");

var Tracker = app.tracker = restful.model('tracker', mongoose.Schema({
    tile: 'string',
}))
.methods(['get', 'post', 'put', 'delete']);

Tracker.register(app, '/trackers');

app.listen(config.port);
```

I can GET resources, and I can POST new data, but fields are not created.
I have only the _id number and the _v tags : 

```
{"_id":"556f75746bac0877700a83a2","__v":0}
```
I have tried with 2 differents RESTful Firefox plugin (  REST Easy & RESTClient ), the result is the same.

My JSON : 
```json
{"title":"test"}
```

Do I miss something ?
Thanks in advance for your help !

Regards,

**Comment by phiphou** [comment]
Make sure you set ContentType to application/json in headers in your REST tester app ...

**Comment by DaveRicho** [comment]
I am having exactly the same problem. I have set Content-Type to application/json

I must be missing something, but am struggling to find the problem. I suspect it might be a problem/conflict with my dependencies as I can get the "resource" example installed and working fine.

My depencies are as follows: 

"dependencies": {
    "body-parser": "^1.12.4",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.12.4",
    "hbs": "~2.9.0",
    "mongodb": ">= 1.3.19",
    "mongoose": "3.8.23",
    "morgan": "~1.5.3",
    "node-restful": "^0.1.18",
    "qs": "^3.1.0",
    "serve-favicon": "~2.2.1"
  }

part of my app.js includes the following:

mongoose.connect("mongodb://localhost/surfers");

var Surfer = app.surfer = restful.model('surfer', mongoose.Schema({
  fname: 'string',
  lname: 'string',
  division: 'string',
  seeding: 'string'
}))
  .methods(['get', 'post', 'put', 'delete']);

Surfer.register(app, '/surfers');

app.use('/', routes);
app.use('/users', users);
app.use('/surfers', surfers);


Thanks in advance if you can see anything obvious.

Kind Regards,

Dave (Newbie to all things js).

**Comment by DaveRicho** [comment]
I just resolved my problem (silly me). I omitted the following from my app.js:

app.use(bodyParser.json());

Thanks again for making such as awesome library!!

Dave.

**Comment by baugarten** [comment]
I don't think this is a problem. Going to close this out. If you see this, it's likely you're forgetting some critical piece of middleware -- please see the README. Otherwise, reopen with a reproducible example and I'll take a look

**Comment by storynory** [comment]
If you are using Postman make sure that you select x-www-form-urlencoded.

**Comment by codxse** [comment]
that the comma, 

```
var Tracker = app.tracker = restful.model('tracker', mongoose.Schema({
    tile: 'string',
}))
```

**Comment by baugarten** [comment]
@codxse not sure I understand your comment.
